"""
Patterns router — sync task-pattern-learning data across devices.

Patterns are small JSON blobs generated by the client-side ML system that
learns how long similar tasks actually take.  Stored per user so they
survive app reinstalls and work across devices.

Endpoints:
  GET  /patterns        — fetch the user's current patterns
  POST /patterns/sync   — full replace (client sends complete authoritative list)
"""

import logging
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, field_validator
from typing import List
from datetime import datetime

from db import get_supabase
from auth import get_current_user_id

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/patterns", tags=["patterns"])


class PatternRow(BaseModel):
    keywords:               List[str]
    average_actual_minutes: int
    sample_size:            int
    accuracy_score:         int = 50

    @field_validator("average_actual_minutes", "sample_size")
    @classmethod
    def non_negative(cls, v: int) -> int:
        if v < 0:
            raise ValueError("Value must be ≥ 0")
        return v

    @field_validator("accuracy_score")
    @classmethod
    def valid_accuracy(cls, v: int) -> int:
        if v < 0 or v > 100:
            raise ValueError("accuracy_score must be between 0 and 100")
        return v


@router.get("")
def get_patterns(user_id: str = Depends(get_current_user_id)):
    """Fetch all patterns for the authenticated user."""
    sb = get_supabase()
    result = (
        sb.table("task_patterns")
        .select("keywords, average_actual_minutes, sample_size, accuracy_score")
        .eq("user_id", user_id)
        .execute()
    )
    return result.data or []


@router.post("/sync", status_code=200)
def sync_patterns(
    patterns: List[PatternRow],
    user_id: str = Depends(get_current_user_id),
):
    """
    Full replace: delete all existing patterns for the user and insert
    the new set.  The client always sends the complete authoritative list.
    Accepts up to 500 patterns per user.
    """
    if len(patterns) > 500:
        raise HTTPException(status_code=400, detail="Max 500 patterns per sync")
    sb = get_supabase()

    # Delete existing patterns for this user
    sb.table("task_patterns").delete().eq("user_id", user_id).execute()

    if not patterns:
        return []

    rows = [
        {
            "user_id":                user_id,
            "keywords":               p.keywords,
            "average_actual_minutes": p.average_actual_minutes,
            "sample_size":            p.sample_size,
            "accuracy_score":         p.accuracy_score,
            "updated_at":             datetime.utcnow().isoformat(),
        }
        for p in patterns
    ]

    result = sb.table("task_patterns").insert(rows).execute()
    logger.info("Synced %d patterns for user %s", len(rows), user_id[:8])
    return result.data or []
