/* AUTO-GENERATED registry — maps Ionicons kebab names -> react-icons/io5.
 * Regenerate rather than hand-editing names. */
import {
  IoAdd,
  IoAddCircle,
  IoAddCircleOutline,
  IoAddOutline,
  IoAirplaneOutline,
  IoAlarmOutline,
  IoAlbumsOutline,
  IoAlertCircleOutline,
  IoAnalyticsOutline,
  IoAppsOutline,
  IoArchiveOutline,
  IoArrowDownOutline,
  IoArrowForward,
  IoArrowForwardCircleOutline,
  IoArrowForwardOutline,
  IoArrowRedoOutline,
  IoArrowUndoOutline,
  IoArrowUp,
  IoArrowUpOutline,
  IoAtOutline,
  IoAttachOutline,
  IoBagOutline,
  IoBanOutline,
  IoBarbellOutline,
  IoBasketOutline,
  IoBatteryChargingOutline,
  IoBedOutline,
  IoBluetoothOutline,
  IoBodyOutline,
  IoBookOutline,
  IoBookmark,
  IoBookmarkOutline,
  IoBriefcaseOutline,
  IoBrushOutline,
  IoBugOutline,
  IoBuildOutline,
  IoBulbOutline,
  IoCafeOutline,
  IoCalendarClearOutline,
  IoCalendarNumberOutline,
  IoCalendar,
  IoCalendarOutline,
  IoCallOutline,
  IoCameraOutline,
  IoCardOutline,
  IoCartOutline,
  IoCashOutline,
  IoChatbubbleOutline,
  IoChatbubblesOutline,
  IoCheckboxOutline,
  IoCheckmark,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoCheckmarkDone,
  IoCheckmarkDoneCircle,
  IoCheckmarkDoneOutline,
  IoCheckmarkOutline,
  IoChevronBack,
  IoChevronBackOutline,
  IoChevronDown,
  IoChevronDownOutline,
  IoChevronForward,
  IoChevronForwardOutline,
  IoChevronUp,
  IoChevronUpOutline,
  IoClipboardOutline,
  IoClose,
  IoCloseCircle,
  IoCloseOutline,
  IoCloudDoneOutline,
  IoCloudOfflineOutline,
  IoCloudOutline,
  IoCloudUploadOutline,
  IoCodeSlashOutline,
  IoCogOutline,
  IoColorPaletteOutline,
  IoColorWandOutline,
  IoCompassOutline,
  IoConstruct,
  IoConstructOutline,
  IoContractOutline,
  IoCopyOutline,
  IoCreateOutline,
  IoCutOutline,
  IoDesktopOutline,
  IoDocumentTextOutline,
  IoDownloadOutline,
  IoDuplicateOutline,
  IoEarthOutline,
  IoEllipse,
  IoEllipseOutline,
  IoEllipsisHorizontal,
  IoEllipsisVertical,
  IoEnterOutline,
  IoExitOutline,
  IoExpandOutline,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFileTrayFullOutline,
  IoFileTrayOutline,
  IoFilmOutline,
  IoFilterOutline,
  IoFingerPrintOutline,
  IoFitnessOutline,
  IoFlag,
  IoFlagOutline,
  IoFlame,
  IoFlameOutline,
  IoFlash,
  IoFlashOutline,
  IoFlashlightOutline,
  IoFlaskOutline,
  IoFolderOutline,
  IoFunnelOutline,
  IoGameControllerOutline,
  IoGiftOutline,
  IoGitBranchOutline,
  IoGlobeOutline,
  IoGridOutline,
  IoHammerOutline,
  IoHandLeftOutline,
  IoHandRightOutline,
  IoHappyOutline,
  IoHardwareChipOutline,
  IoHeadsetOutline,
  IoHeart,
  IoHeartDislikeOutline,
  IoHeartOutline,
  IoHelpCircleOutline,
  IoHomeOutline,
  IoHourglass,
  IoHourglassOutline,
  IoImageOutline,
  IoImagesOutline,
  IoInformationCircleOutline,
  IoKeyOutline,
  IoLaptopOutline,
  IoLayersOutline,
  IoLeafOutline,
  IoLibraryOutline,
  IoLinkOutline,
  IoListOutline,
  IoLocationOutline,
  IoLockClosed,
  IoLockOpenOutline,
  IoLogInOutline,
  IoLogOutOutline,
  IoMailOpenOutline,
  IoMailOutline,
  IoMapOutline,
  IoMedalOutline,
  IoMegaphoneOutline,
  IoMenuOutline,
  IoMicOutline,
  IoMoon,
  IoMoonOutline,
  IoMoveOutline,
  IoMusicalNote,
  IoMusicalNotesOutline,
  IoNavigateOutline,
  IoNewspaperOutline,
  IoNotificationsOutline,
  IoOptionsOutline,
  IoPartlySunnyOutline,
  IoPencil,
  IoPencilOutline,
  IoPeopleOutline,
  IoPerson,
  IoPersonCircleOutline,
  IoPersonOutline,
  IoPhonePortraitOutline,
  IoPinOutline,
  IoPizzaOutline,
  IoPlanetOutline,
  IoPlayCircle,
  IoPlayOutline,
  IoPowerOutline,
  IoPricetagOutline,
  IoPricetagsOutline,
  IoPrintOutline,
  IoPulseOutline,
  IoRadioButtonOn,
  IoRainyOutline,
  IoReaderOutline,
  IoRefreshOutline,
  IoRemove,
  IoRemoveCircle,
  IoRemoveCircleOutline,
  IoRemoveOutline,
  IoReorderThreeOutline,
  IoReorderTwoOutline,
  IoRepeat,
  IoRepeatOutline,
  IoResizeOutline,
  IoRestaurantOutline,
  IoReturnDownBackOutline,
  IoReturnUpForwardOutline,
  IoRibbonOutline,
  IoRocketOutline,
  IoSadOutline,
  IoSaveOutline,
  IoSchoolOutline,
  IoSearchOutline,
  IoSettingsOutline,
  IoShareOutline,
  IoShareSocialOutline,
  IoShieldCheckmarkOutline,
  IoShieldOutline,
  IoShirtOutline,
  IoSnowOutline,
  IoSparkles,
  IoSparklesOutline,
  IoSquareOutline,
  IoStar,
  IoStarHalf,
  IoStarOutline,
  IoStopOutline,
  IoStopwatchOutline,
  IoSunny,
  IoSunnyOutline,
  IoSwapVertical,
  IoSwapVerticalOutline,
  IoSyncOutline,
  IoTerminalOutline,
  IoTextOutline,
  IoThumbsDownOutline,
  IoThumbsUpOutline,
  IoThunderstormOutline,
  IoTimeOutline,
  IoTimerOutline,
  IoTrash,
  IoToday,
  IoTodayOutline,
  IoTrashOutline,
  IoTrendingDownOutline,
  IoTrendingUpOutline,
  IoTrophyOutline,
  IoTvOutline,
  IoUnlinkOutline,
  IoVideocamOutline,
  IoVolumeHighOutline,
  IoWalkOutline,
  IoWaterOutline,
  IoWalletOutline,
  IoWifiOutline,
  IoWineOutline,
} from 'react-icons/io5';
import type { IconType } from 'react-icons';

export const ICONS: Record<string, IconType> = {
  'add': IoAdd,
  'add-circle': IoAddCircle,
  'add-circle-outline': IoAddCircleOutline,
  'add-outline': IoAddOutline,
  'airplane-outline': IoAirplaneOutline,
  'alarm-outline': IoAlarmOutline,
  'albums-outline': IoAlbumsOutline,
  'alert-circle-outline': IoAlertCircleOutline,
  'analytics-outline': IoAnalyticsOutline,
  'apps-outline': IoAppsOutline,
  'archive-outline': IoArchiveOutline,
  'arrow-down-outline': IoArrowDownOutline,
  'arrow-forward': IoArrowForward,
  'arrow-forward-circle-outline': IoArrowForwardCircleOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'arrow-redo-outline': IoArrowRedoOutline,
  'arrow-undo-outline': IoArrowUndoOutline,
  'arrow-up': IoArrowUp,
  'arrow-up-outline': IoArrowUpOutline,
  'at-outline': IoAtOutline,
  'attach-outline': IoAttachOutline,
  'bag-outline': IoBagOutline,
  'ban-outline': IoBanOutline,
  'barbell-outline': IoBarbellOutline,
  'basket-outline': IoBasketOutline,
  'battery-charging-outline': IoBatteryChargingOutline,
  'bed-outline': IoBedOutline,
  'bluetooth-outline': IoBluetoothOutline,
  'body-outline': IoBodyOutline,
  'book-outline': IoBookOutline,
  'bookmark': IoBookmark,
  'bookmark-outline': IoBookmarkOutline,
  'briefcase-outline': IoBriefcaseOutline,
  'brush-outline': IoBrushOutline,
  'bug-outline': IoBugOutline,
  'build-outline': IoBuildOutline,
  'bulb-outline': IoBulbOutline,
  'cafe-outline': IoCafeOutline,
  'calendar-clear-outline': IoCalendarClearOutline,
  'calendar-number-outline': IoCalendarNumberOutline,
  'calendar': IoCalendar,
  'calendar-outline': IoCalendarOutline,
  'call-outline': IoCallOutline,
  'camera-outline': IoCameraOutline,
  'card-outline': IoCardOutline,
  'cart-outline': IoCartOutline,
  'cash-outline': IoCashOutline,
  'chatbubble-outline': IoChatbubbleOutline,
  'chatbubbles-outline': IoChatbubblesOutline,
  'checkbox-outline': IoCheckboxOutline,
  'checkmark': IoCheckmark,
  'checkmark-circle': IoCheckmarkCircle,
  'checkmark-circle-outline': IoCheckmarkCircleOutline,
  'checkmark-done': IoCheckmarkDone,
  'checkmark-done-circle': IoCheckmarkDoneCircle,
  'checkmark-done-outline': IoCheckmarkDoneOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'chevron-back': IoChevronBack,
  'chevron-back-outline': IoChevronBackOutline,
  'chevron-down': IoChevronDown,
  'chevron-down-outline': IoChevronDownOutline,
  'chevron-forward': IoChevronForward,
  'chevron-forward-outline': IoChevronForwardOutline,
  'chevron-up': IoChevronUp,
  'chevron-up-outline': IoChevronUpOutline,
  'clipboard-outline': IoClipboardOutline,
  'close': IoClose,
  'close-circle': IoCloseCircle,
  'close-outline': IoCloseOutline,
  'cloud-done-outline': IoCloudDoneOutline,
  'cloud-offline-outline': IoCloudOfflineOutline,
  'cloud-outline': IoCloudOutline,
  'cloud-upload-outline': IoCloudUploadOutline,
  'code-slash-outline': IoCodeSlashOutline,
  'cog-outline': IoCogOutline,
  'color-palette-outline': IoColorPaletteOutline,
  'color-wand-outline': IoColorWandOutline,
  'compass-outline': IoCompassOutline,
  'construct': IoConstruct,
  'construct-outline': IoConstructOutline,
  'contract-outline': IoContractOutline,
  'copy-outline': IoCopyOutline,
  'create-outline': IoCreateOutline,
  'cut-outline': IoCutOutline,
  'desktop-outline': IoDesktopOutline,
  'document-text-outline': IoDocumentTextOutline,
  'download-outline': IoDownloadOutline,
  'duplicate-outline': IoDuplicateOutline,
  'earth-outline': IoEarthOutline,
  'ellipse': IoEllipse,
  'ellipse-outline': IoEllipseOutline,
  'ellipsis-horizontal': IoEllipsisHorizontal,
  'ellipsis-vertical': IoEllipsisVertical,
  'enter-outline': IoEnterOutline,
  'exit-outline': IoExitOutline,
  'expand-outline': IoExpandOutline,
  'eye-off-outline': IoEyeOffOutline,
  'eye-outline': IoEyeOutline,
  'file-tray-full-outline': IoFileTrayFullOutline,
  'file-tray-outline': IoFileTrayOutline,
  'film-outline': IoFilmOutline,
  'filter-outline': IoFilterOutline,
  'finger-print-outline': IoFingerPrintOutline,
  'fitness-outline': IoFitnessOutline,
  'flag': IoFlag,
  'flag-outline': IoFlagOutline,
  'flame': IoFlame,
  'flame-outline': IoFlameOutline,
  'flash': IoFlash,
  'flash-outline': IoFlashOutline,
  'flashlight-outline': IoFlashlightOutline,
  'flask-outline': IoFlaskOutline,
  'folder-outline': IoFolderOutline,
  'funnel-outline': IoFunnelOutline,
  'game-controller-outline': IoGameControllerOutline,
  'gift-outline': IoGiftOutline,
  'git-branch-outline': IoGitBranchOutline,
  'globe-outline': IoGlobeOutline,
  'grid-outline': IoGridOutline,
  'hammer-outline': IoHammerOutline,
  'hand-left-outline': IoHandLeftOutline,
  'hand-right-outline': IoHandRightOutline,
  'happy-outline': IoHappyOutline,
  'hardware-chip-outline': IoHardwareChipOutline,
  'headset-outline': IoHeadsetOutline,
  'heart': IoHeart,
  'heart-dislike-outline': IoHeartDislikeOutline,
  'heart-outline': IoHeartOutline,
  'help-circle-outline': IoHelpCircleOutline,
  'home-outline': IoHomeOutline,
  'hourglass': IoHourglass,
  'hourglass-outline': IoHourglassOutline,
  'image-outline': IoImageOutline,
  'images-outline': IoImagesOutline,
  'information-circle-outline': IoInformationCircleOutline,
  'key-outline': IoKeyOutline,
  'laptop-outline': IoLaptopOutline,
  'layers-outline': IoLayersOutline,
  'leaf-outline': IoLeafOutline,
  'library-outline': IoLibraryOutline,
  'link-outline': IoLinkOutline,
  'list-outline': IoListOutline,
  'location-outline': IoLocationOutline,
  'lock-closed': IoLockClosed,
  'lock-open-outline': IoLockOpenOutline,
  'log-in-outline': IoLogInOutline,
  'log-out-outline': IoLogOutOutline,
  'mail-open-outline': IoMailOpenOutline,
  'mail-outline': IoMailOutline,
  'map-outline': IoMapOutline,
  'medal-outline': IoMedalOutline,
  'megaphone-outline': IoMegaphoneOutline,
  'menu-outline': IoMenuOutline,
  'mic-outline': IoMicOutline,
  'moon': IoMoon,
  'moon-outline': IoMoonOutline,
  'move-outline': IoMoveOutline,
  'musical-note': IoMusicalNote,
  'musical-notes-outline': IoMusicalNotesOutline,
  'navigate-outline': IoNavigateOutline,
  'newspaper-outline': IoNewspaperOutline,
  'notifications-outline': IoNotificationsOutline,
  'options-outline': IoOptionsOutline,
  'partly-sunny-outline': IoPartlySunnyOutline,
  'pencil': IoPencil,
  'pencil-outline': IoPencilOutline,
  'people-outline': IoPeopleOutline,
  'person-circle-outline': IoPersonCircleOutline,
  'person': IoPerson,
  'today': IoToday,
  'today-outline': IoTodayOutline,
  'person-outline': IoPersonOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'pin-outline': IoPinOutline,
  'pizza-outline': IoPizzaOutline,
  'planet-outline': IoPlanetOutline,
  'play-circle': IoPlayCircle,
  'play-outline': IoPlayOutline,
  'power-outline': IoPowerOutline,
  'pricetag-outline': IoPricetagOutline,
  'pricetags-outline': IoPricetagsOutline,
  'print-outline': IoPrintOutline,
  'pulse-outline': IoPulseOutline,
  'radio-button-on': IoRadioButtonOn,
  'rainy-outline': IoRainyOutline,
  'reader-outline': IoReaderOutline,
  'refresh-outline': IoRefreshOutline,
  'remove': IoRemove,
  'remove-circle': IoRemoveCircle,
  'remove-circle-outline': IoRemoveCircleOutline,
  'remove-outline': IoRemoveOutline,
  'reorder-three-outline': IoReorderThreeOutline,
  'reorder-two-outline': IoReorderTwoOutline,
  'repeat': IoRepeat,
  'repeat-outline': IoRepeatOutline,
  'resize-outline': IoResizeOutline,
  'restaurant-outline': IoRestaurantOutline,
  'return-down-back-outline': IoReturnDownBackOutline,
  'return-up-forward-outline': IoReturnUpForwardOutline,
  'ribbon-outline': IoRibbonOutline,
  'rocket-outline': IoRocketOutline,
  'sad-outline': IoSadOutline,
  'save-outline': IoSaveOutline,
  'school-outline': IoSchoolOutline,
  'search-outline': IoSearchOutline,
  'settings-outline': IoSettingsOutline,
  'share-outline': IoShareOutline,
  'share-social-outline': IoShareSocialOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'shield-outline': IoShieldOutline,
  'shirt-outline': IoShirtOutline,
  'snow-outline': IoSnowOutline,
  'sparkles': IoSparkles,
  'sparkles-outline': IoSparklesOutline,
  'square-outline': IoSquareOutline,
  'star': IoStar,
  'star-half': IoStarHalf,
  'star-outline': IoStarOutline,
  'stop-outline': IoStopOutline,
  'stopwatch-outline': IoStopwatchOutline,
  'sunny': IoSunny,
  'sunny-outline': IoSunnyOutline,
  'swap-vertical': IoSwapVertical,
  'swap-vertical-outline': IoSwapVerticalOutline,
  'sync-outline': IoSyncOutline,
  'terminal-outline': IoTerminalOutline,
  'text-outline': IoTextOutline,
  'thumbs-down-outline': IoThumbsDownOutline,
  'thumbs-up-outline': IoThumbsUpOutline,
  'thunderstorm-outline': IoThunderstormOutline,
  'time-outline': IoTimeOutline,
  'timer-outline': IoTimerOutline,
  'trash': IoTrash,
  'trash-outline': IoTrashOutline,
  'trending-down-outline': IoTrendingDownOutline,
  'trending-up-outline': IoTrendingUpOutline,
  'trophy-outline': IoTrophyOutline,
  'tv-outline': IoTvOutline,
  'unlink-outline': IoUnlinkOutline,
  'videocam-outline': IoVideocamOutline,
  'volume-high-outline': IoVolumeHighOutline,
  'walk-outline': IoWalkOutline,
  'water-outline': IoWaterOutline,
  'wallet-outline': IoWalletOutline,
  'wifi-outline': IoWifiOutline,
  'wine-outline': IoWineOutline,
};
